name: Scheduled Merge Remote Action

on: 
  schedule:
    - cron: '17 2 * * *'
    # every day at 02:17
  workflow_dispatch:

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Rebase from Upstream
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git remote add upstream git@github.com:UberGuidoZ/Flipper.git
          git fetch upstream
          git rebase upstream/main
          git push
